/**
 * About APSettingPage css file zhuyu 2018/8/23
 */

import {
  StyleSheet,
  Dimensions,
} from 'react-native';

const {
  width,
  height,
} = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  mainView: {
    flex: 1,
    backgroundColor: '#fff',
  },
  bottomButtonView: {
    width: width,
    height: 60,
    backgroundColor: '#fff',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    borderTopWidth: 1,
    borderColor: '#ddd',
    paddingLeft: 40,
    paddingRight: 40,
  },
  saveSettingButtonView: {
    width: 100,
    height: 40,
    borderColor: '#ddd',
    borderWidth: 1,
    borderRadius: 20,
    backgroundColor: '#464646',
  },
  saveSettingButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveSettingButtonTextStyle: {
    color: '#fff',
    fontSize: 16,
  },
  titleView: {
    width: width,
    height: 40,
    borderWidth: 1,
    borderColor: '#ddd',
    paddingLeft: 15,
    paddingRight: 15,
    flexDirection: 'row',
  },
  titleTextView: {
    flex: 7,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    // backgroundColor: 'green',
  },
  titleButtonView: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    // backgroundColor: 'red',
  },
  titleText: {
    fontSize: 16,
    color: '#000',
  },
  titleButton: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',

  },
  titleIcon: {
    fontSize: 20,
    color: '#000',
  },
  networkSettingView: {
    width: width,
    // height: 150,
    // backgroundColor: 'brown',
    padding: 15,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: '#ddd',
  },
  networkSettingProtocolView: {
    flex: 1,
    // height: 40,
    // backgroundColor: 'green',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  networkSettingDetailInputTitle: {
    flex: 2,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  networkSettingDetailInputTitleText: {
    fontSize: 16,
    color: '#000',
  },
  networkSettingDetailInput: {
    flex: 3,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  networkSettingDetailPPPOEView: {
    flex: 2,
    // backgroundColor: 'pink',
    // flexDirection: 'row',
    // justifyContent: 'flex-start',
    // alignItems: 'center',
  },
  networkSettingDetailInputView: {
    flex: 1,
    // height: 40,
    // backgroundColor: 'blue',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  networkSettingDetailInputStyle: {
    flex: 1,
  },
  networkSettingProtocolPicker: {
    flex: 1,
  },
  networkSettingDetailStaticView: {
    flex: 5,
  },
  wifiSettingView: {
    width: width,
    // height: 150,
    // backgroundColor: 'brown',
    padding: 15,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: '#ddd',
  },
  wifiSettingFlatListRenderItem: {
    // width: width,
    flex: 1,
    height: 60,
    borderBottomWidth: 1,
    borderColor: '#ddd',
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#fff',
  },
  wifiSettingFlatListRenderItemIconView: {
    flex: 2,
    padding: 5,
    justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor: 'red',
  },
  wifiSettingFlatListRenderItemInfoView: {
    flex: 12,
    // backgroundColor: 'green',
    justifyContent: 'center',
    borderColor: '#000',
    // borderWidth: 1,
    // borderTopWidth: 0,
    // borderBottomWidth: 0,
    paddingLeft: 15,
  },
  wifiSettingFlatListRenderItemArrowButtonView: {
    flex: 2,
    // backgroundColor: 'blue',
    // justifyContent: 'center',
    // alignItems: 'center',
  },
  wifiSettingFlatListRenderItemArrowButton: {
    flex: 1,
    // backgroundColor: 'brown',
    justifyContent: 'center',
    alignItems: 'center',
  },
  wifiSettingFlatListRenderItemIcon: {
    fontSize: 30,
    color: '#000',
  },
  wifiSettingFlatListRenderItemArrowIcon: {
    fontSize: 30,
    color: '#000',
  },
  wifiSettingFlatListRenderItemInfo: {
    color: '#000',
    fontSize: 16,
  },
  advanceSettingView: {
    width: width,
    // height: 150,
    // backgroundColor: 'brown',
    padding: 15,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: '#ddd',
  },
  advanceSettingTitleView: {
    height: 40,
    // flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRightWidth: 0,
    borderLeftWidth: 0,
    // backgroundColor: 'red',
  },
  advanceSettingTitle: {
    color: '#000',
    fontSize: 16,
  },
  radioPicker: {
    flex: 1,
  },
  radioSettingView: {
    height: 160,
    // flex: 1,
    // backgroundColor: 'red',
  },
  radioSettingModeView: {
    height: 80,
  },
  passwdInputPartView: {
    flex: 9,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  passwdIconPartView: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },

  modalBackView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 30,
    // backgroundColor: 'red',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  changeHistoryModalView: {
    width: width - 60,
    height: height - 200,
    backgroundColor: '#fff',
    borderColor: '#000',
    borderWidth: 1,
    // backgroundColor: 'gray',
  },
  changeHistoryModalInfoView: {
    flex: 1,
    // justifyContent: 'flex-start',
    // alignItems: 'center',
    // backgroundColor: 'blue',
    // paddingBottom: 40,
    // paddingTop: 40,
  },
  changeHistoryModalListHeaderComponentView: {
    // flex: 1,
    height: 40,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#ddd',
    borderBottomWidth: 1,
    // backgroundColor: 'red',
  },
  changeHistoryModalListFooterComponentView: {
    // flex: 1,
    height: 40,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#ddd',
    borderTopWidth: 1,
    // backgroundColor: 'green',
    marginBottom: 0,
  },
  changeHistoryModalListFooterComponentButton: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    // backgroundColor: 'brown',
  },
  changeHistoryListEmptyComponentView: {
    // backgroundColor: 'blue',
    height: height - 280,
  },
  changeHistoryRenderItemView: {
    height: 40,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  attrNameView: {
    flex: 2,
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingLeft: 15,
    // backgroundColor: 'red',
  },
  attrChangeDetailView: {
    flex: 3,
    justifyContent: 'center',
    alignItems: 'flex-start',
    paddingLeft: 15,
    // backgroundColor: 'blue',
  },
  changeHistoryItemSeparatorComponentView: {
    flex: 1,
    height: 1,
    borderColor: '#ddd',
    borderTopWidth: 1,
  },

  modalTextStyle: {
    color: '#000',
    fontSize: 16,
  },
});
